// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwuowxkrylskyjcljrlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3dW93eGtyeWxza3lqY2xqcmxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDQyMzgsImV4cCI6MjA2Njg4MDIzOH0.eqyKi5qYZ5pSbmVJutzuaZLXlVgTUeW-ubdptmby30c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});